services:
  - type: web
    name: sample-service-name
    env: python
    buildCommand: "yarn build"
    startCommand: "gunicorn wsgi --chdir ./src/"
    envVars:
      - key: BASENAME
        value: "/"
      - key: FLASK_APP
        value: "src/app.py"
      - key: FLASK_DEBUG
        value: "0"
      - key: FLASK_APP_KEY
        value: "any key works"
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: postgresql-trapezoidal-42170
      #     property: connectionString
      - key: BACKEND_URL
        value: "http://your-backend-url"  # Update this to the actual backend URL

# databases:
#   - name: postgresql-trapezoidal-42170
#     region: ohio
#     ipAllowList: []
#     plan: free
