services:
  - type: web
    name: chef-dojo-frontend
    env: static
    buildCommand: "yarn build"
    staticPublishPath: build
    envVars:
      - key: BASENAME
        value: "/"
      - key: FLASK_APP
        value: "src/app.py"
      - key: FLASK_DEBUG
        value: "0"
      - key: FLASK_APP_KEY
        value: "any key works"
      # - key: BACKEND_URL
      #   value: "https://chef-dojo-backend-b16a71e8fca3.herokuapp.com"

# Uncomment and configure if you are using a database
# databases:
#   - name: postgresql-trapezoidal-42170
#     region: ohio
#     ipAllowList: []
#     plan: free
